### ISSUE TITLE
作者，能不能看一下QQ邮箱！

### ISSUE THREAD

**Issue by yadangongzhu** [Jxpro/ca-web#1]
大佬，俺已经把我的问题发送带你的QQ邮箱了。

**Comment by Jxpro** [comment]
你好，对于你的问题：
### 1. 新用户注册，默认分配的role是admin，该怎么变成user？

这个是未完善的设计，注册的用户应该默认为user，具体来说可以尝试将src/api/user.js文件中register函数的authority: 0部分修改为role:'user'，然后切换admin权限暂时需要在数据库中手动调整或自己另外实现接口。

###  2. 提交新用户注册信息，出现如下提示，但user表中还是成功创建了用户。

![image](https://github.com/Jxpro/ca-web/assets/87376573/d19e2879-06bc-47a6-90ce-5dc2451da0a0)

后端是否部署在本地？可能是端口或者防火墙的问题导致前端未接受到响应，具体请阅读或提供后端java程序日志截图，看有没有什么报错信息，或者使用浏览器开发中工具查看http请求
 
### 3. 用户申请证书提交信息过程中，在第二步“Public Key”提交显示“服务器繁忙”，卡住过不去了。两个参数是不是两个大素数？

- 对于RSA来说，其参数n要求是2048位的大素数，参数e一般都固定选择为65537
- 对于EC-prime256v1来说，其私钥是一个点，两个参数均为256位的点坐标

### 4. 这两个是不是服务器的证书和私钥？请问一下最开始这两个是怎么生成的？
 
![image](https://github.com/Jxpro/ca-web/assets/87376573/e5a477e1-930d-4d56-8442-7b973912e9c1)

是的，crt为证书，privateKey为私钥，生成的过程涉及ASN.1编码和X.509证书格式规范。

简单来说，ASN.1是一种抽象的二进制数据编码规则。X.509证书格式除了公钥，还包含了序列号，签名，用法等多个部分。

证书生成的过程可以描述为，将X.509证书包含的内容以ASN.1规则进行编码后，再将以二进制表示的证书数据使用base64编码成文本内容并加入分隔符。

具体编码细节可以参考我的另一个项目：[x509-utils](https://github.com/Jxpro/x509-utils)

相关参考文献：

ASN.1：
- https://zh.wikipedia.org/wiki/ASN.1
- https://lapo.it/asn1js/

X.509：
- https://www.cnblogs.com/charlieroro/p/10948173.html
- https://www.cnblogs.com/jiangzhaowei/p/9346993.html

**Comment by yadangongzhu** [comment]
拜谢
[Uploading question-2.docx…]()

**Comment by yadangongzhu** [comment]
[question-2.docx](https://github.com/Jxpro/ca-web/files/15455833/question-2.docx)

**Comment by yadangongzhu** [comment]
[question-2.docx](https://github.com/Jxpro/ca-web/files/15455851/question-2.docx)

**Comment by Jxpro** [comment]
下次直接把问题贴上来，下载文件很麻烦，同时不方便别人参考

---

### npm start启动前端，页面跳出来之后，没有做任何操作，浏览器已经提示“服务器繁忙了”

浏览器使用开发者工具查看响应状态

### 申请证书，在“public  key”出现的报错
 
src\pages\CertApply\PubKey\index.js 修改选项字段：

<Select.Option value="RSA-2048">RSA-2048</Select.Option>
<Select.Option value="EC-prime256v1">EC-prime256v1</Select.Option>

改为

<Select.Option value="RSA">RSA-2048</Select.Option>
<Select.Option value="EC">EC-prime256v1</Select.Option>

自己对照一下数据库的sql文件，报错已经明确表明了数据库字段不对应，自己看着调整一下

**Comment by yadangongzhu** [comment]
好的，万分感谢！已成功运行
